language: php
os:
  - linux
  - windows

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
matrix:
  include:
    - php: 5.3
      dist: precise

before_script:
  - git --version
  - composer install --prefer-dist --dev